version: '3.4'

services:
  eventshowcase.api:
    image: ${DOCKER_REGISTRY-}eventshowcaseapi
    build:
      context: .
      dockerfile: EventShowcase.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080" 
      - "5001:8081"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - database_data:/var/lib/postgresql/data 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    image: front
    ports:
      - "3000:3000" 
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - eventshowcase.api
  
volumes:
  database_data:
    driver: local
